# Dockerfile
FROM python:3.9-slim-buster

COPY main.py /app/main.py

COPY env.py /app/env.py

COPY run.sh /app/run.sh

COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["bash", "/app/run.sh"]
