# my-python-job.yaml.j2
apiVersion: batch/v1
kind: Job
metadata:
  name: my-python-job
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: oes52/myjob:latest
        env:
        - name: PYCODE
          value: "def main() : \n\tprint('Hello! world')\n\tprint('Goodbye! world')\n\treturn 'byebye'"
      restartPolicy: Never
  backoffLimit: 1
